version: '3'
services:
  sonarqube:
    image: sonarqube:lts-community
    hostname: sonarqube
    container_name: sonarqube
    read_only: true
    links:
      - sonar-db
    depends_on:
      sonar-db:
        condition: service_healthy
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonar-db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
      TZ: "Asia/Shanghai"
      SONAR_WEB_JAVAOPTS: "-Xmx256m -Xms256m"
      ONAR_CE_JAVAOPTS: "-Xmx512m -Xms512m"
      NSTALL4J_ADD_VM_PARAMS: "-Xms1024m -Xmx1024m -XX:MaxDirectMemorySize=512m -Djava.util.prefs.userRoot=/nexus-data/javaprefs"
    volumes:
      - /opt/sonar/data:/opt/sonarqube/data
      - /opt/sonar/extensions:/opt/sonarqube/extensions
      - /opt/sonar/logs:/opt/sonarqube/logs
      - /opt/sonar/temp:/opt/sonarqube/temp
    ports:
      - "9888:9000"
    networks:
      - sonar
  sonar-db:
    image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/postgres:15.4
    privileged: true
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    hostname: sonar-db
    container_name: sonar-db
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - /opt/postgresql:/var/lib/postgresql
      - /opt/postgresql/data:/var/lib/postgresql/data
    networks:
      - sonar
networks:
  sonar: