version: '3.1'

services:

  wordpress:
    image: wordpress:5
    restart: always
    ports:
      - 28080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: snowkscp
      WORDPRESS_DB_PASSWORD: 5201314snowmm
      WORDPRESS_DB_NAME: snowkscpdb
      WORDPRESS_CONFIG_EXTRA: |
        /* Multisite */
        define('WP_ALLOW_MULTISITE', true );
        define('MULTISITE', true);
        define('SUBDOMAIN_INSTALL', false);
        define('DOMAIN_CURRENT_SITE', 'blog.snowks.cn'); // TODO: change to actual domain when deploying
        define('PATH_CURRENT_SITE', '/');
        define('SITE_ID_CURRENT_SITE', 1);
        define('BLOG_ID_CURRENT_SITE', 1);
    volumes:
      - /opt/wordpress/web:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: snowkscpdb
      MYSQL_USER: snowkscp
      MYSQL_PASSWORD: 5201314snowmm
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - /opt/wordpress/mysql:/var/lib/mysql
